### ISSUE TITLE
Vote Closes Time Value Missing

### ISSUE THREAD

**Issue by CFWHISPERER** [FreeosDAO/UX_template#4]
A few things happened with voting.

Firstly when looking at the screen initially it shows "Vote Open" but a no-entry logo when moused over, after I clicked it, that went away.

Once I clicked the screen refreshed and there was no time-value in there, after again around 30 seconds that cleared up, screenshots attached
![2022-01-23)voteClosesNoTimeValue](https://user-images.githubusercontent.com/728102/150702453-7075f6a8-4fc1-4785-bbe9-5bc2a6f86d2c.png)
![2022-01-23)voteClosesNoTimeValue-01](https://user-images.githubusercontent.com/728102/150702454-2552449c-12ff-45e3-a72a-3a12f4115b34.png)
.

**Comment by andyzal** [comment]
I will correct that.

**Comment by CFWHISPERER** [comment]
This is now fixed.
