### ISSUE TITLE
Ratify Remain Time Flashes "less then one minute" on Browser Refresh.

### ISSUE THREAD

**Issue by CFWHISPERER** [FreeosDAO/UX_template#5]
With 7 minutes to go to Ratify, dialog shows "less then one minute" momentarily then corrects.  (Note the use of then and not than).

**Comment by CFWHISPERER** [comment]
This happens in both Brave and Microsoft Edge browsers.

**Comment by andyzal** [comment]
Enforcing refresh on page makes mess. In 30 sec. this mess clean up automatically. Should manual refresh be blocked? Or should be worked out another solution? Topic for discussion anyway.

**Comment by CFWHISPERER** [comment]
This is now fixed.
